### ISSUE TITLE
Documentation page not responding

### ISSUE THREAD

**Issue by mudrd8mz** [SN-RECIT-formation-a-distance/moodle-filter_recitautolink#1]
The filter description mentions https://recitfad.ca/moodledocs/ as the page with more details. I have problems loading the page and I am getting "The connection has timed out" when trying to open it.

**Comment by gustavobazzo** [comment]
For now, this website https://recitfad.ca/moodledocs/  is only available in Canada. We have added at least one Youtube video to explain more about the use of the plugin.
