### ISSUE TITLE
Callback before_standard_top_of_body_html in filter_recitactivity component should be migrated to new hook callback for core\hook\output\before_standard_top_of_body_html_generation

### ISSUE THREAD

**Issue by leac** [SN-RECIT-formation-a-distance/moodle-filter_recitautolink#10]
When debug is turned on, I get the following message:

Callback before_standard_top_of_body_html in filter_recitactivity component should be migrated to new hook callback for core\hook\output\before_standard_top_of_body_html_generation

I was able to fix the code in my testing environment. Would you like a PR?

**Comment by gustavobazzo** [comment]
Hi @leac,

Thank you for your comment.
We are currently migrating our plugins to Moodle 4.5.
We should release the new version in a few months.

Kind regards!
